import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SiteFooter } from "../components/blocks/site-footer";
import {
  SiteHeader,
  type NavigationLink,
} from "../components/blocks/site-header";
import "./theme.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationLinks: NavigationLink[] = [
  { name: "Home", href: "/" },
  { name: "Translator", href: "/translator" },
  { name: "Chart", href: "/chart" },
  { name: "Learn", href: "/learn-practice" },
  { name: "Fun", href: "/applications-fun" },
  { name: "Community", href: "/community" },
  { name: "Resources", href: "/about-resources" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col bg-[var(--background)] text-[var(--foreground)] antialiased`}
      >
        <SiteHeader navigation={navigationLinks} />
        <main className="flex-1">{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
